# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EOSC FAIR4S
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  FAIR4S is the skills and capability framework that was developed in Workpackage
  7 in the European Open Science Cloud (EOSC) pilot project. FAIR4S aims to help
  research communities and research institutions implement Research Data Management
  and FAIR stewardship in the open science and data science context.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github:  https://github.com/EOSC-FAIR4S/eosc-fair4s.github.io
framework_github: https://github.com/EOSC-FAIR4S/fair4s-framework

cookie_accept_message: Thanks!

# Build settings
markdown: kramdown

# These are the images used for the parallax background
parallax_image_one: assets/images/background1.png 
parallax_image_two: assets/images/background1.png

plugins:
  - jekyll-feed

collections: 
  roles: 
    output: true
    layout: role
    permalink: /role-profiles/:path/
  materials:
    output: true
    layout: material
    permalink: /materials/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - fair4s/
  - fair4s/roles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
